services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - node_modules_server:/app/node_modules
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_server:
  node_modules_client: